project:
  type: website
  output-dir: docs

website:
  title: "Tai Do"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd
      - teaching.qmd
      - resources.qmd
      - pets.qmd

format:
  html:
    theme: 
      light: lux
      dark: Solar
    css: styles.css
    toc: true
    page-layout: article

editor: visual

