---
title: "Research"
---

## Research Endeavors

My interests intersect psychology, sociology, social psychology, education, and education and psychological measurement. This page will highlight my research endeavors (work-in-progress). Please also visit my [google scholar](https://scholar.google.com/citations?hl=en&user=kAJcm38AAAAJ&view_op=list_works&sortby=pubdate) page for a formal list of my publications.

Notably, in training to become an applied social and educational psychologist and measurement specialist, I receive a great deal of education and support from many mentors. I hope to highlight them on this page so that you receive more nuance on who I am as a researcher, practitioner, and advocate.

For open-access readings and/or conference/workshop proposals, please visit: <https://conservancy.umn.edu/browse?type=author&value=Do,%20Tai>

## Research Projects

***COMING SOON***

## Research Labs

### Dr. Geoffrey Maruyama (Advisor) - Social and Developmental Processes

[**Description:**]{.underline}We are focused on achievement processes in schools, particularly on social processes and on antecedents of educational success; on research methods for educational and other applied settings; and recently, on action research approaches in challenged communities and engaged scholarship in urban settings.

<https://www.cehd.umn.edu/edpsych/research/labs/maruyama/>

### **Dr. Michael Rodriguez (Mentor) - Minnesota Youth Development Research Group**

[**Description:**]{.underline} We explore methodological and substantive challenges in youth development, relying on the tenets of positive psychology, ecological perspectives of youth development, and the translation of research to practice. We also do this work in the spirit of elevating youth voice, practicing elements of socio-cultural psychometrics.

<https://sites.google.com/view/mnydrg>

### Dr. Rashné Jehangir - First-Generation Institute

[**Description:**]{.underline}We are centered around increasing access and success for first-generation college students, graduate students, first-generation employees, and faculty across higher education and initiatives and programs. We work to address systemic barriers rooted in racism and classism while also forwarding an asset-based praxis that recognizes the capital and ways of knowing that first-generation students bring to higher education.

<https://www.cehd.umn.edu/olpd/research-and-engagement/firstgen/>

### Dr. Richard Lee - Race, Ethnicity, Migration, and Mental Health

[Description:]{.underline} We are interested in the ways in which race, ethnicity, and migration relate to the development, well-being, and mental health of individuals and families from diverse cultural backgrounds. Much of the work has been with diverse Asian American populations, but is expanding to many different minoritized and immigrant populations.

<https://famileelab.wordpress.com/current-and-past-research/>

## In addition, With Boundless Gratitude

In no order - and will keep adding as I keep on navigating:

Dr. Martin Van Boekel; Dr. Jeff Bye; Dr. Krista Soria; Dr. Isabel Lopez-Hurtado; Dr. Rik Lamm; Dr. Jose Palma; Dr. Kyle Nickodem; Dr. Terra Molengraff; Dr. Kelly Collins; Dr. Christine Wu; Dr. Andy Furco; Dr. Michael Stebleton; Dr. Regina Langhout; Dr. Stacey Horn; Dr. Andrew Ziefller; Dr. Keisha Varma; Dr. Ashley Hufnagle; Dr. Mireya Smith; Dr. Jonathan Brown; Dr. Alexander Champoux-Crowley; Dr. Erin Crowley-Champoux; Dr. Vimal Rao; Dr. Nicolaas VanMeerten; Dr. Annie Hansen-Burke; Dr. Jessie Kember; Dr. Melissa Vélez

Carlos Chavez, Shelby Weisen, Isa Peczuh, Jieyi Cai; Victoria Wee; Shujianing Li; Zer Vang, Cathy Ngo; Kory Vue; Tayler Marks (Loiselle); Alejandra Miranda; Corissa Rohloff; Liz Ancel; Regina Lisinker; Risa Luther; Daniel Lama; Indah Wahyuni; Miguel Ovies-Bocanegra; Pablo Vivas Corrales; Ali Fulsher; Megan Goeke; Jen Doll
