---
title: "Resources"
---

*More Coming Soon*

-   Information on community-engagement and service-learning: [Z.umn.edu/CAUSE](z.umn.edu/CAUSE)

-   Survival resources navigating higher education as students from underrepresented backgrounds: <http://www.theunguide.org>

-   Op-ed: Why institutional narratives about first-gen students matter: <https://www.insidehighered.com/views/2022/08/30/conversation-first-gen-student-belonging-and-identities-opinion>

## Students

### University of Minnesota

**The Aurora Center;** Website: [aurora.umn.edu](http://aurora.umn.edu/)

-   Description: Provides a safe and confidential space for students, faculty, staff, alumni, and family members or friends affiliated with the University of Minnesota, TC or Augsburg College who are victims/survivors/concerned people of sexual assault, relationship violence, or stalking.

**Boynton Health Service;** Website: <http://www.bhs.umn.edu/>

-   Description: Provides mental health counseling in addition to SCS.

**Center for Writing;** Website: [writing.umn.edu/](http://writing.umn.edu/)

-   Description: Resource for general writing assistance.

**The Disability Resource Center;** Website: <https://diversity.umn.edu/disability/>

-   Description: Collaborates with students who have disabilities to provide and/or arrange accommodations.

**Immigration Response Team;** Website: [immigration.umn.edu/](http://immigration.umn.edu/)

-   Description: Provides resources and support to the greater University community on the impact of executive orders and other policy changes, immigration regulations, and issues connected with DACA and immigration status.

**International Student and Scholar Services;** Website: <http://www.isss.umn.edu/>

-   Description: Provides advising and counseling to foreign nationals about academic, immigration, legal, career, financial, personal and family issues, as well as issues of cross-cultural adjustment and professional integration upon returning to home countries.

**Student Counseling Services;** Website: [counseling.umn.edu](http://counseling.umn.edu/)

-   Description: SCS promotes student success through individual and group counseling, along with classes, workshops, and presentations.

**Nutritious U Pantry; Website:** <https://boynton.umn.edu/food-pantry>

-   Description: Provides fresh and healthy food to students that struggle to get enough to eat.

## Researchers/Faculty

## Practitioners/Administrators
