---
title: "Teaching Endeavors"
---

## Courses

My purpose for this page is share the courses that I have taught either as instructor of record, teaching assistant, or guest lecturer.

### Psychology of Multiculturalism in Education (Instructor of Record)

This course examines contemporary and historical perspectives on issues of social and cultural diversity in the United States, with special **emphasis on issues of race, ethnicity, gender, social class, ability, sexual orientation, and religious diversity**. Processes of oppression, stereotyping, prejudice, and social perception biases are the primary topics of the course. The course develops a context in which participants develop insights in the personal nature of prejudice while they study the propagation of prejudice in school culture and social structures. The insights of how and why prejudices develop help participants to understand their interactions with "diverse" others and form competencies and sensitivities related to multicultural issues of diversity. The course presents models for personal and educational change that confront issues of racism, sexism, homophobia, and disability insensitivity.

[***Course Goals, Objectives, and Expectations***]{.underline}

-   Develop an awareness of multicultural issues in educational settings.

-   Identify how aspects of culture influence their daily lives.

-   Use critical thinking skills to examine how power and privilege affect their lives and society at large. 

-   Be able to identify and implement strategies for reducing bias and affirming diverse cultures in the classroom and everyday life. 

-   Be able to consider complex multicultural topics from both an educational, cultural, and psychological lens.

[***Student Learning Outcomes***]{.underline}

-   Can locate and critically evaluate information

-   Understand diverse philosophies and cultures within and across societies

-   Understand psychological, educational, and cultural mechanisms in student experiences and learning

-   Understand ways to assess, evaluate, and measure student learning and education with respect to cross-cultural goals

### Learning Cognition and Assessment (Synchronous Teaching Assistant)

In this course you will learn about: Theories of child development and how they relate to approaches to instruction; Behaviorist, cognitive, and social cognitive learning theories; Approaches to instruction and assessment (teacher-centered vs. student-centered vs. assessment-centered); and Issues related to assessment and measuring student learning (validity, reliability, interpretation, etc.) by participating in assessment design (traditional, performance, formative) and interpretation.

### Community Engaged Research in K-12 School Settings

In this course, you will learn how to design and enact research projects related to teaching and learning in K-12 schools.  The course content will cover theories of learning, cognition, and development and will focus on how these theories explain how students learn and inform teaching practices.  The course will feature guest lectures from university faculty from multiple departments and centers including The Center for Applied Research and Development, The Department of Curriculum and Instruction and the Department of Educational Psychology.

### Intelligence and Creativity (Asynchronous Online Teaching Assistant)

In this course, we will examine theories of intelligence and creativity, their development, and their implications for educational practices and psychological research. This course is part of the certification program in gifted education and talented education. 

### Gifted and Talented Education (Asynchronous Online Teaching Assistant)

This course will provide an overview of the study of the gifted and talented and their education. Among those topics are cognitive and affective characteristics of gifted and talented students, the identification of gifted and talented, curricular and instructional issues, and parental and social relationships. This course should interest graduate and undergraduate students as well as educators, counselors, and other interested parties who want to learn about the gifted and talented and their education. In this course, we will examine theories of giftedness, talent development, instructional strategies, diversity and technological issues, implications for educational practices and psychological inquiry, and international considerations.
